swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.virtual-wallet.io"
basePath: "/api"
tags:
- name: "Accounts"
  description: "Everything about accounts"
- name: "Account"
  description: "Everything about your account"
- name: "Users"
  description: "All about users"
- name: "User"
  description: "Everything about a user"
- name: "Transaction"
  description: "Everything about transactions"
schemes:
- "https"
paths:

  /users:

    get:
      tags:
        - "Users"
      summary: "Get all users"
      operationId: "getUsers"
      security:
        - wallet_auth:
          - "read:users"

    post:
      tags:
        - "Users"
      summary: "Create new user"
      operationId: "createUser"
      deprecated: false
      security:
        - wallet_auth:
          - "write:users"
  
  /users/{userId}:

    get:
      tags:
        - "User"
      summary: "User details"
      operationId: "getUser"
      deprecated: false
      security:
        - wallet_auth:
          - "read-user"

    delete:
      tags:
        - "User"
      summary: "Delete user"
      operationId: "deleteUser"
      deprecated: false
      security:
        - wallet_auth:
          - "write-user"
    
    post:
      tags:
        - "User"
      summary: "Create account for user"
      operationId: "createAccountForUser"
      deprecated: false
      security:
        - wallet_auth:
          - "write-user"
  
  /users/{userId}/{accountId}:

    get:
      tags:
        - "User"
      summary: "User Account details"
      operationId: "getUserAccount"
      deprecated: false
      security:
        - wallet_auth:
          - "read-account"
    
    delete:
      tags:
        - "User"
      summary: "Close User Account"
      operationId: "closeUserAccount"
      deprecated: false
      security:
        - wallet_auth:
          - "write-account"
    
    post:
      tags:
        - "User"
      summary: "Create User Account Transaction"
      operationId: "createUserAccountTransaction"
      deprecated: false
      security:
        - wallet_auth:
          - "write-account"
  
  /users/{userId}/{accountId}/{transactionId}:

    get:
      tags:
        - "User"
      summary: "User Transaction details"
      operationId: "getUserTransaction"
      deprecated: false
      security:
        - wallet_auth:
          - "read-user"

    delete:
      tags:
        - "User"
      summary: "Reverse Transaction"
      operationId: "reverseUserTransaction"
      deprecated: false
      security:
        - wallet_auth:
          - "write-user"

  /accounts:

    post:
      tags:
      - "Accounts"
      summary: "Create a new account"
      description: ""
      operationId: "addAccount"
      security:
      - wallet_auth:
        - "write:account"
        - "read:account"

    get:
      tags:
      - "Accounts"
      summary: "Get all accounts"
      description: ""
      operationId: "getAccount"
      security:
      - wallet_auth:
        - "write:account"
        - "read:account"

  /accounts/{accountId}:

    get:
      tags:
      - "Account"
      summary: "Get details of account"
      description: ""
      operationId: "getAccountDetails"
      security:
      - wallet_auth:
        - "write:account"
        - "read:account"

    delete:
      tags:
      - "Account"
      summary: "Close account"
      description: ""
      operationId: "closeAccount"
      security:
        - wallet_auth:
          - "write:account"
    
    post:
      tags:
      - "Account"
      summary: "Create a new transaction"
      description: ""
      operationId: "createAccountTransaction"
      security:
        - wallet_auth:
          - "write:transaction"
      
  /accounts/{accountId}/{transactionId}:

    get:
      tags:
        - "Account"
      summary: "Get transaction details"
      operationId: "getUserTransactionDetails"
      deprecated: false
      security:
        - wallet_auth:
          - "read:transaction"

    delete:
      tags:
        - "Account"
      summary: "Reverse transaction"
      deprecated: false
      security:
        - wallet_auth:
          - "write:transaction"

  /transactions:

    get:
      tags:
      - "Transaction"
      summary: "Get all transactions"
      description: ""
      operationId: "getTransactions"
      security:
      - wallet_auth:
        - "write:transactions"
        - "read:transactions"

    post:
      tags:
      - "Transaction"
      summary: "Create a new transaction"
      description: ""
      operationId: "createTransaction"
      security:
        - wallet_auth:
          - "write:transaction"
      
  /transactions/{transactionId}:

    get:
      tags:
        - "Transaction"
      summary: "Get transaction details"
      operationId: "getTransactionDetails"
      deprecated: false
      security:
        - wallet_auth:
          - "read:transaction"

    delete:
      tags:
        - "Transaction"
      summary: "Reverse transaction"
      deprecated: false
      security:
        - wallet_auth:
          - "write:transaction"

  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
securityDefinitions:
  wallet_auth:
    type: "oauth2"
    authorizationUrl: "https://www.virtual-wallet.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:user: "modify user"
      read:user: "read user"
      write:account: "modify account"
      read:account: "read your account"
      write:transaction: "modify transaction"
      read:transaction: "read transaction"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"