application:
  swagger:
    enabled: true
    regexPathExclusion: (/actuator.*|/error.*)
    version: @project.version@
    title: @project.name@
    description: Swagger documentation for @project.description@
    license:
    contact:
      name: Virtual Wallet Team
      email: NOREFUNDS@wallet.bbd

#  logging:
#    level:
#      org.springframework: ERROR
#      com.mkyong: DEBUG
#    pattern:
#      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#      file: "%d %p %c{1.} [%t] %m%n"
#    file: app.log